// examples/react-vite/src/App.tsx
import { FlipperWidget, type FlipperEventMap } from "@flipperdotfamily/react";
import { useEffect, useMemo, useState } from "react";
import { erc20Abi, formatUnits } from "viem";
import { useBalance, useConnect, useConnection, useConnectors, useDisconnect, useReadContracts, useWalletClient } from "wagmi";
import { DEV_WALLET_ID, type ShowcaseToken, type Stack } from "./showcase";

// The tokens Lagoon lets its users flip (the widget's `tokens` allowlist), by symbol. $FLIPPER and ETH are always on.
const LAGOON_TOKENS = ["FLIPPER", "Degen", "BNKR", "PONS"];

interface Activity {
  flipId: string;
  symbol: string;
  amount: string;
  status: "pending" | "won" | "lost" | "refunded";
  payout?: string;
  at: number;
}
interface Toast {
  id: number;
  tone: "win" | "loss" | "info";
  title: string;
  body: string;
}

const fmt = (wei: string | bigint, decimals: number) => {
  const n = Number(formatUnits(BigInt(wei), decimals));
  return n >= 1e6 ? `${(n / 1e6).toFixed(2)}M` : n >= 1e3 ? `${(n / 1e3).toFixed(1)}K` : n.toLocaleString(undefined, { maximumFractionDigits: 4 });
};
const short = (a: string) => `${a.slice(0, 6)}…${a.slice(-4)}`;

export function App({ stack }: { stack: Stack }) {
  const { address } = useConnection();
  const { data: walletClient } = useWalletClient();
  const { mutate: disconnect } = useDisconnect();
  const [picking, setPicking] = useState(false);
  const [tokens, setTokens] = useState<ShowcaseToken[] | null>(null);
  const [activity, setActivity] = useState<Activity[]>([]);
  const [toasts, setToasts] = useState<Toast[]>([]);

  useEffect(() => {
    // Lagoon's list, or (on a chain without those tokens) the first few listed ones
    Promise.all([stack.findTokens(LAGOON_TOKENS), stack.listTokens()])
      .then(([mine, all]) => setTokens(mine.length > 2 ? mine : [...mine, ...all.filter((t) => !mine.some((m) => m.address === t.address))].slice(0, 5)))
      .catch(() => setTokens([]));
  }, [stack]);
  const allowlist = useMemo(
    () => [...new Set([stack.addresses.flipper, "ETH", ...(tokens ?? []).map((t) => t.address)].filter(Boolean))],
    [tokens, stack],
  );

  // portfolio: ETH plus the allowlisted tokens
  const eth = useBalance({ address, query: { enabled: !!address } });
  const balances = useReadContracts({
    contracts: (tokens ?? []).map((t) => ({ address: t.address, abi: erc20Abi, functionName: "balanceOf", args: [address!] }) as const),
    query: { enabled: !!address && !!tokens?.length },
  });

  const toast = (t: Omit<Toast, "id">) => {
    const id = Date.now() + Math.random();
    setToasts((all) => [...all, { ...t, id }]);
    setTimeout(() => setToasts((all) => all.filter((x) => x.id !== id)), 5000);
  };

  const onRequested = (d: FlipperEventMap["flip-requested"]) => {
    setActivity((a) => [{ flipId: d.flipId, symbol: d.symbol, amount: fmt(d.amount, d.decimals), status: "pending", at: Date.now() }, ...a]);
    toast({ tone: "info", title: "Flip sent", body: `${fmt(d.amount, d.decimals)} ${d.symbol}: waiting for the coin.` });
  };
  const onSettled = (d: FlipperEventMap["flip-settled"]) => {
    const status = d.outcome;
    setActivity((a) => {
      const row = { flipId: d.flipId, symbol: d.symbol, amount: fmt(d.amount, d.decimals), status, payout: d.won ? fmt(d.payout, d.decimals) : undefined, at: Date.now() };
      return a.some((x) => x.flipId === d.flipId) ? a.map((x) => (x.flipId === d.flipId ? { ...x, ...row } : x)) : [row, ...a];
    });
    toast(
      d.pending
        ? { tone: "win", title: "You won", body: `Your ${d.symbol} stake is back. The winnings are being paid out.` }
        : d.won
        ? { tone: "win", title: "You won", body: `+${fmt(d.payout, d.decimals)} ${d.symbol} landed in your wallet.` }
        : status === "refunded"
          ? { tone: "info", title: "Refunded", body: `Your ${d.symbol} stake came back.` }
          : { tone: "loss", title: "Tails", body: `${fmt(d.amount, d.decimals)} ${d.symbol} went to the house.` },
    );
    void eth.refetch();
    void balances.refetch();
  };

  const rows = (tokens ?? []).map((t, i) => ({ token: t, balance: balances.data?.[i]?.result as bigint | undefined }));

  return (
    <div className="shell">
      <aside className="side">
        <a className="logo" href="#">
          <Wave /> Lagoon
        </a>
        <nav>
          {["Overview", "Swap", "Pools", "Flip", "Activity"].map((n) => (
            <a key={n} href="#" className={n === "Flip" ? "on" : undefined} aria-current={n === "Flip" ? "page" : undefined}>
              {n}
              {n === "Flip" && <span className="new">new</span>}
            </a>
          ))}
        </nav>
        <div className="net">
          <span className="dot" /> {stack.chainName}
          <small>chain {stack.chainId}</small>
        </div>
      </aside>

      <div className="main">
        <header className="top">
          <div>
            <h1>Flip</h1>
            <p>Double or nothing on the tokens Lagoon supports. Settles onchain in seconds.</p>
          </div>
          {address ? (
            <button className="acct" onClick={() => disconnect()} title="Disconnect">
              <span className="dot" />
              {short(address)}
            </button>
          ) : (
            <button className="btn" onClick={() => setPicking(true)}>
              Connect wallet
            </button>
          )}
        </header>

        <div className="cols">
          <section className="panel portfolio">
            <h2>Your tokens</h2>
            {!address ? (
              <p className="muted">Connect a wallet to see your balances.</p>
            ) : (
              <ul className="tokens">
                <li>
                  <Avatar symbol={stack.nativeSymbol} />
                  <span className="sym">{stack.nativeSymbol}</span>
                  <span className="num">{eth.data ? fmt(eth.data.value, 18) : "–"}</span>
                </li>
                {rows.map(({ token, balance }) => (
                  <li key={token.address}>
                    <Avatar symbol={token.symbol} logo={token.logo} />
                    <span className="sym">{token.symbol}</span>
                    <span className="num">{balance !== undefined ? fmt(balance, token.decimals) : "–"}</span>
                  </li>
                ))}
              </ul>
            )}
          </section>

          <section className="flip">
            {tokens && (
              <FlipperWidget
                walletClient={walletClient ?? null}
                onConnectRequest={() => setPicking(true)}
                chainId={stack.chainId}
                deploymentUrl={stack.deploymentUrl}
                mode="picker"
                tokens={allowlist}
                token={stack.addresses.flipper}
                variant="card"
                partner="lagoon"
                theme={{
                  mode: "dark",
                  accent: "#7c5cff",
                  radius: 20,
                  background: "#0e1430",
                  surface: "#131a3a",
                  field: "#0b1027",
                  border: "#ffffff14",
                }}
                onFlipRequested={onRequested}
                onFlipSettled={onSettled}
                onError={(e) => console.warn("flipper:", e.message)}
              />
            )}
          </section>

          <section className="panel activity">
            <h2>Activity</h2>
            {activity.length === 0 ? (
              <p className="muted">Your flips show up here as they happen.</p>
            ) : (
              <ul className="feed" data-testid="activity">
                {activity.map((a) => (
                  <li key={a.flipId} data-status={a.status}>
                    <span className={`badge ${a.status}`}>{a.status === "pending" ? "flipping" : a.status}</span>
                    <span>
                      {a.amount} {a.symbol}
                    </span>
                    <span className="muted">{a.payout ? `+${a.payout}` : `#${a.flipId}`}</span>
                  </li>
                ))}
              </ul>
            )}
          </section>
        </div>
      </div>

      {picking && <ConnectModal onClose={() => setPicking(false)} />}
      <div className="toasts" aria-live="polite">
        {toasts.map((t) => (
          <div key={t.id} className={`toast ${t.tone}`}>
            <b>{t.title}</b>
            <span>{t.body}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

/** Lagoon's wallet picker: wagmi's EIP-6963 connectors. */
function ConnectModal({ onClose }: { onClose: () => void }) {
  const connectors = useConnectors();
  const { mutate: connect, isPending, error } = useConnect();
  return (
    <div className="modal" role="dialog" aria-modal="true" aria-label="Connect a wallet" onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div className="sheet">
        <div className="sheet-head">
          <h3>Connect a wallet</h3>
          <button className="x" onClick={onClose} aria-label="Close">
            ×
          </button>
        </div>
        {connectors.length === 0 && <p className="muted">No browser wallet found. Install one, such as Rabby or MetaMask.</p>}
        <div className="wallets">
          {connectors.map((c) => (
            <button key={c.uid} className="wallet" disabled={isPending} onClick={() => connect({ connector: c }, { onSuccess: onClose })}>
              {c.icon ? <img src={c.icon} alt="" /> : <Avatar symbol={c.name} />}
              <span>{c.name}</span>
              {c.id === DEV_WALLET_ID && <span className="dev">DEV · local fork</span>}
            </button>
          ))}
        </div>
        {error && <p className="err">{error.message.split("\n")[0]}</p>}
      </div>
    </div>
  );
}

function Avatar({ symbol, logo }: { symbol: string; logo?: string | null }) {
  if (logo) return <img className="avatar" src={logo} alt="" />;
  const hue = [...symbol].reduce((h, c) => h + c.charCodeAt(0) * 37, 0) % 360;
  return (
    <span className="avatar" style={{ background: `hsl(${hue} 70% 55%)` }}>
      {symbol.slice(0, 1)}
    </span>
  );
}

function Wave() {
  return (
    <svg width="28" height="28" viewBox="0 0 32 32" aria-hidden="true">
      <rect width="32" height="32" rx="9" fill="#7c5cff" />
      <path d="M5 19c4-4 7-4 11 0s7 4 11 0" fill="none" stroke="#fff" strokeWidth="3" strokeLinecap="round" />
      <path d="M5 12c4-4 7-4 11 0s7 4 11 0" fill="none" stroke="#ffffff80" strokeWidth="3" strokeLinecap="round" />
    </svg>
  );
}

// examples/vue-vite/src/App.vue
<script setup lang="ts">
import { FlipperWidget, type FlipperEventMap, type FlipperStrings } from "@flipperdotfamily/vue";
import { useConnect, useConnection, useConnectorClient, useConnectors, useDisconnect } from "@wagmi/vue";
import { formatUnits } from "viem";
import { ref, shallowRef } from "vue";
import { DEV_WALLET_ID, type Stack } from "./showcase";

defineProps<{ stack: Stack }>();

const { address } = useConnection();
const connectors = useConnectors();
const { mutate: connect, isPending, error } = useConnect();
const { mutate: disconnect } = useDisconnect();
// the connected wallet as a viem client (undefined while disconnected: the widget runs read-only)
const { data: walletClient } = useConnectorClient();

const widget = shallowRef<{ open(): void; close(): void }>();
const picking = ref(false);
let reopen = false;

// Questline's voice: every built-in string can be replaced (see FlipperStrings)
const strings: Partial<FlipperStrings> = {
  flip: "Double {amount} {symbol}",
  flipAgain: "Go again",
  won: "Loot doubled!",
  lost: "The house takes this round.",
  openWidget: "Bonus flip",
};

// The bonus flip lives in a modal. When it asks for a wallet, step out of it, connect, then come back.
function onConnectRequest() {
  reopen = true;
  widget.value?.close();
  picking.value = true;
}
function pick(c: (typeof connectors.value)[number]) {
  connect(
    { connector: c },
    {
      onSuccess: () => {
        picking.value = false;
        if (reopen) setTimeout(() => widget.value?.open(), 50);
        reopen = false;
      },
    },
  );
}

interface Loot {
  flipId: string;
  text: string;
  won: boolean;
}
const log = ref<Loot[]>([]);
const onSettled = (d: FlipperEventMap["flip-settled"]) => {
  const amount = Number(formatUnits(BigInt(d.amount), d.decimals)).toLocaleString(undefined, { maximumFractionDigits: 2 });
  const text = d.pending ? `Won ${amount} ${d.symbol}, paying out…` : d.won ? `Doubled ${amount} ${d.symbol}` : `Lost ${amount} ${d.symbol}`;
  // a pending win settles twice (winnings on their way, then paid): one row per flip
  log.value = [{ flipId: d.flipId, won: d.won, text }, ...log.value.filter((l) => l.flipId !== d.flipId)];
};

const quests = [
  { name: "Win 3 ranked matches", done: 2, of: 3, xp: 250 },
  { name: "Open 5 loot crates", done: 5, of: 5, xp: 150 },
  { name: "Collect 1,000 gold", done: 640, of: 1000, xp: 200 },
  { name: "Squad up with a friend", done: 0, of: 1, xp: 120 },
];
const short = (a: string) => `${a.slice(0, 6)}…${a.slice(-4)}`;
</script>

<template>
  <header class="bar">
    <div class="wrap bar-in">
      <a class="logo" href="#">
        <svg viewBox="0 0 32 32" width="30" height="30" aria-hidden="true">
          <rect width="32" height="32" rx="9" fill="#6d4aff" />
          <path d="M16 5l9 4v7c0 6-4 9-9 11-5-2-9-5-9-11V9z" fill="#ffb36b" />
          <path d="M16 10v13" stroke="#6d4aff" stroke-width="2.5" stroke-linecap="round" />
        </svg>
        Questline
      </a>
      <nav><a href="#" class="on">Quests</a><a href="#">Leaderboard</a><a href="#">Shop</a></nav>
      <div class="me">
        <span class="lvl"><b>Lv 12</b><i><em style="width: 64%"></em></i></span>
        <button v-if="address" class="chip" title="Disconnect" @click="disconnect()">{{ short(address) }}</button>
        <button v-else class="cta" @click="picking = true">Connect wallet</button>
      </div>
    </div>
  </header>

  <main class="wrap">
    <section class="season">
      <div>
        <span class="tag">Season 3 · 12 days left</span>
        <h1>Tides of Fortune</h1>
        <p>Finish quests, earn loot, and flip it in the bonus round. Heads doubles it.</p>
      </div>
      <div class="pass">
        <span>Season pass</span>
        <b>Tier 18 <small>/ 40</small></b>
        <i><em style="width: 45%"></em></i>
      </div>
    </section>

    <div class="grid">
      <section class="card">
        <h2>Daily quests</h2>
        <ul class="quests">
          <li v-for="q in quests" :key="q.name" :class="{ done: q.done >= q.of }">
            <div class="q-top">
              <span>{{ q.name }}</span>
              <b>+{{ q.xp }} XP</b>
            </div>
            <i><em :style="{ width: `${Math.min(100, (q.done / q.of) * 100)}%` }"></em></i>
            <small>{{ q.done >= q.of ? "Complete" : `${q.done.toLocaleString()} / ${q.of.toLocaleString()}` }}</small>
          </li>
        </ul>
      </section>

      <section class="card vault">
        <div class="chest" aria-hidden="true">
          <svg viewBox="0 0 120 90" width="120" height="90">
            <rect x="10" y="38" width="100" height="46" rx="8" fill="#ff9a3d" />
            <path d="M10 44a50 26 0 0 1 100 0z" fill="#ffb36b" />
            <rect x="10" y="40" width="100" height="8" fill="#6d4aff" />
            <rect x="52" y="36" width="16" height="22" rx="4" fill="#ffe08a" stroke="#6d4aff" stroke-width="3" />
            <circle cx="30" cy="20" r="5" fill="#ffe08a" /><circle cx="92" cy="14" r="4" fill="#ffe08a" /><circle cx="70" cy="8" r="3" fill="#ffe08a" />
          </svg>
        </div>
        <h2>Bonus round</h2>
        <p>Flip any token in your wallet, double or nothing. It's provably fair and settles onchain.</p>
        <!-- the widget as a button: it opens the flip card in a modal -->
        <FlipperWidget
          ref="widget"
          variant="button"
          button-label="Bonus flip: double your loot"
          :wallet-client="walletClient ?? null"
          :strings="strings"
          @connect-request="onConnectRequest"
          @flip-settled="onSettled"
          @error="(e) => console.warn('flipper:', e.message)"
        />
        <h3>Loot log</h3>
        <ul v-if="log.length" class="log" data-testid="loot-log">
          <li v-for="l in log" :key="l.flipId" :class="l.won ? 'won' : 'lost'">{{ l.text }}</li>
        </ul>
        <p v-else class="muted">Your bonus flips show up here.</p>
      </section>
    </div>
  </main>

  <div v-if="picking" class="modal" @click.self="picking = false">
    <div class="sheet" role="dialog" aria-modal="true" aria-label="Connect a wallet">
      <h3>Connect a wallet</h3>
      <p v-if="!connectors.length" class="muted">No browser wallet found. Install one, such as Rabby or MetaMask.</p>
      <button v-for="c in connectors" :key="c.uid" class="wallet" :disabled="isPending" @click="pick(c)">
        <img v-if="c.icon" :src="c.icon" alt="" />
        <span>{{ c.name }}</span>
        <span v-if="c.id === DEV_WALLET_ID" class="dev">DEV · local fork</span>
      </button>
      <p v-if="error" class="err">{{ error.message.split("\n")[0] }}</p>
    </div>
  </div>
</template>
